version: '3.8'

services:
  frontend:
    container_name: conduit_frontend
    build:
      context: ../build/frontend
      args:
        - UPSTREAM=http://backend:${HTTP_PORT}/api
    ports:
      - "8000:80"
    restart: on-failure
    depends_on:
      - backend

  backend:
    container_name: conduit_backend
    build:
      context: ..
      dockerfile: build/backend/Dockerfile
      args:
        LDFLAGS: ${LDFLAGS}
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - migrator
  
  migrator:
    container_name: conduit_migrator
    build:
      context: ..
      dockerfile: build/migrator/Dockerfile
      args:
        GOOSE_VERSION: ${GOOSE_VERSION:-3.6.0}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DBNAME
      - POSTGRES_SSLMODE
    restart: on-failure
    volumes:
      - ../migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.0-alpine
    container_name: conduit_postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}
      interval: 1s
      timeout: 3s
      retries: 15

volumes:
  db_data: