---
run:
  concurency: 4
  deadline: 2m
  issues-exit-code: 1
  skip-files:
    - "vendor/*"

output:
  format: tab
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    - exhaustruct
    - exhaustivestruct
    - nosprintfhostport
    - gochecknoglobals
    - forbidigo
  fast: false

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake

issues:
  exclude-use-default: false
  max-issues-per-linter: 100
  max-same-issues: 4
  new: false
